logsources:
  apache:
    category: webserver
    sources:
      - 'File:/var/log/apache/*.log'
      - 'File:/var/log/apache2/*.log'
      - 'File:/var/log/httpd/*.log'
  linux-auth:
    product: linux
    service: auth
    sources:
      - 'File:/var/log/auth.log'
      - 'File:/var/log/auth.log.?' # auth.log.1, auth.log.2, ...
  linux-syslog:
    product: linux
    service: syslog
    sources:
      - 'File:/var/log/syslog'
      - 'File:/var/log/syslog.?' # syslog.1, syslog.2 ...
